export type WorldCurrencyEntry = {
  code: string;
  name: string;
  countries: string;
};

export const WORLD_CURRENCIES: WorldCurrencyEntry[] = [
  { code: 'USD', name: 'United States Dollar', countries: 'United States, Puerto Rico, Ecuador, El Salvador' },
  { code: 'EUR', name: 'Euro', countries: 'Germany, France, Italy, Spain, Netherlands, Belgium, Austria, Ireland, Finland, Portugal, Greece, Luxembourg' },
  { code: 'GBP', name: 'British Pound Sterling', countries: 'United Kingdom, England, Scotland, Wales' },
  { code: 'INR', name: 'Indian Rupee', countries: 'India' },
  { code: 'JPY', name: 'Japanese Yen', countries: 'Japan' },
  { code: 'AUD', name: 'Australian Dollar', countries: 'Australia' },
  { code: 'CAD', name: 'Canadian Dollar', countries: 'Canada' },
  { code: 'CHF', name: 'Swiss Franc', countries: 'Switzerland, Liechtenstein' },
  { code: 'CNY', name: 'Chinese Yuan Renminbi', countries: 'China' },
  { code: 'HKD', name: 'Hong Kong Dollar', countries: 'Hong Kong' },
  { code: 'SGD', name: 'Singapore Dollar', countries: 'Singapore' },
  { code: 'NZD', name: 'New Zealand Dollar', countries: 'New Zealand' },
  { code: 'KRW', name: 'South Korean Won', countries: 'South Korea, Korea' },
  { code: 'MXN', name: 'Mexican Peso', countries: 'Mexico' },
  { code: 'BRL', name: 'Brazilian Real', countries: 'Brazil' },
  { code: 'ZAR', name: 'South African Rand', countries: 'South Africa' },
  { code: 'AED', name: 'UAE Dirham', countries: 'United Arab Emirates, Dubai, Abu Dhabi' },
  { code: 'SAR', name: 'Saudi Riyal', countries: 'Saudi Arabia' },
  { code: 'QAR', name: 'Qatari Riyal', countries: 'Qatar' },
  { code: 'KWD', name: 'Kuwaiti Dinar', countries: 'Kuwait' },
  { code: 'BHD', name: 'Bahraini Dinar', countries: 'Bahrain' },
  { code: 'OMR', name: 'Omani Rial', countries: 'Oman' },
  { code: 'JOD', name: 'Jordanian Dinar', countries: 'Jordan' },
  { code: 'EGP', name: 'Egyptian Pound', countries: 'Egypt' },
  { code: 'TRY', name: 'Turkish Lira', countries: 'Turkey, Türkiye' },
  { code: 'ILS', name: 'Israeli New Shekel', countries: 'Israel' },
  { code: 'THB', name: 'Thai Baht', countries: 'Thailand' },
  { code: 'MYR', name: 'Malaysian Ringgit', countries: 'Malaysia' },
  { code: 'IDR', name: 'Indonesian Rupiah', countries: 'Indonesia' },
  { code: 'PHP', name: 'Philippine Peso', countries: 'Philippines' },
  { code: 'VND', name: 'Vietnamese Dong', countries: 'Vietnam' },
  { code: 'TWD', name: 'New Taiwan Dollar', countries: 'Taiwan' },
  { code: 'PKR', name: 'Pakistani Rupee', countries: 'Pakistan' },
  { code: 'BDT', name: 'Bangladeshi Taka', countries: 'Bangladesh' },
  { code: 'LKR', name: 'Sri Lankan Rupee', countries: 'Sri Lanka' },
  { code: 'NPR', name: 'Nepalese Rupee', countries: 'Nepal' },
  { code: 'MMK', name: 'Myanmar Kyat', countries: 'Myanmar, Burma' },
  { code: 'KHR', name: 'Cambodian Riel', countries: 'Cambodia' },
  { code: 'LAK', name: 'Lao Kip', countries: 'Laos' },
  { code: 'SEK', name: 'Swedish Krona', countries: 'Sweden' },
  { code: 'NOK', name: 'Norwegian Krone', countries: 'Norway' },
  { code: 'DKK', name: 'Danish Krone', countries: 'Denmark' },
  { code: 'ISK', name: 'Icelandic Króna', countries: 'Iceland' },
  { code: 'PLN', name: 'Polish Zloty', countries: 'Poland' },
  { code: 'CZK', name: 'Czech Koruna', countries: 'Czech Republic, Czechia' },
  { code: 'HUF', name: 'Hungarian Forint', countries: 'Hungary' },
  { code: 'RON', name: 'Romanian Leu', countries: 'Romania' },
  { code: 'BGN', name: 'Bulgarian Lev', countries: 'Bulgaria' },
  { code: 'HRK', name: 'Croatian Kuna', countries: 'Croatia' },
  { code: 'RSD', name: 'Serbian Dinar', countries: 'Serbia' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', countries: 'Ukraine' },
  { code: 'GEL', name: 'Georgian Lari', countries: 'Georgia' },
  { code: 'RUB', name: 'Russian Ruble', countries: 'Russia' },
  { code: 'KZT', name: 'Kazakh Tenge', countries: 'Kazakhstan' },
  { code: 'UZS', name: 'Uzbekistani Som', countries: 'Uzbekistan' },
  { code: 'XAF', name: 'Central African CFA Franc', countries: 'Cameroon, Chad, Central African Republic, Republic of Congo, Gabon, Equatorial Guinea' },
  { code: 'XOF', name: 'West African CFA Franc', countries: 'Senegal, Mali, Ivory Coast, Burkina Faso, Niger, Togo, Benin, Guinea-Bissau' },
  { code: 'NGN', name: 'Nigerian Naira', countries: 'Nigeria' },
  { code: 'GHS', name: 'Ghanaian Cedi', countries: 'Ghana' },
  { code: 'KES', name: 'Kenyan Shilling', countries: 'Kenya' },
  { code: 'UGX', name: 'Ugandan Shilling', countries: 'Uganda' },
  { code: 'TZS', name: 'Tanzanian Shilling', countries: 'Tanzania' },
  { code: 'ETB', name: 'Ethiopian Birr', countries: 'Ethiopia' },
  { code: 'RWF', name: 'Rwandan Franc', countries: 'Rwanda' },
  { code: 'MAD', name: 'Moroccan Dirham', countries: 'Morocco' },
  { code: 'TND', name: 'Tunisian Dinar', countries: 'Tunisia' },
  { code: 'DZD', name: 'Algerian Dinar', countries: 'Algeria' },
  { code: 'LYD', name: 'Libyan Dinar', countries: 'Libya' },
  { code: 'MUR', name: 'Mauritian Rupee', countries: 'Mauritius' },
  { code: 'ZMW', name: 'Zambian Kwacha', countries: 'Zambia' },
  { code: 'MZN', name: 'Mozambican Metical', countries: 'Mozambique' },
  { code: 'BWP', name: 'Botswana Pula', countries: 'Botswana' },
  { code: 'NAD', name: 'Namibian Dollar', countries: 'Namibia' },
  { code: 'AOA', name: 'Angolan Kwanza', countries: 'Angola' },
  { code: 'CDF', name: 'Congolese Franc', countries: 'Democratic Republic of Congo, DRC' },
  { code: 'ARS', name: 'Argentine Peso', countries: 'Argentina' },
  { code: 'CLP', name: 'Chilean Peso', countries: 'Chile' },
  { code: 'COP', name: 'Colombian Peso', countries: 'Colombia' },
  { code: 'PEN', name: 'Peruvian Sol', countries: 'Peru' },
  { code: 'UYU', name: 'Uruguayan Peso', countries: 'Uruguay' },
  { code: 'PYG', name: 'Paraguayan Guarani', countries: 'Paraguay' },
  { code: 'BOB', name: 'Bolivian Boliviano', countries: 'Bolivia' },
  { code: 'VES', name: 'Venezuelan Bolívar', countries: 'Venezuela' },
  { code: 'DOP', name: 'Dominican Peso', countries: 'Dominican Republic' },
  { code: 'CRC', name: 'Costa Rican Colón', countries: 'Costa Rica' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', countries: 'Guatemala' },
  { code: 'HNL', name: 'Honduran Lempira', countries: 'Honduras' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', countries: 'Nicaragua' },
  { code: 'PAB', name: 'Panamanian Balboa', countries: 'Panama' },
  { code: 'JMD', name: 'Jamaican Dollar', countries: 'Jamaica' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', countries: 'Trinidad and Tobago' },
  { code: 'BBD', name: 'Barbadian Dollar', countries: 'Barbados' },
  { code: 'FJD', name: 'Fijian Dollar', countries: 'Fiji' },
  { code: 'PGK', name: 'Papua New Guinean Kina', countries: 'Papua New Guinea' },
  { code: 'XPF', name: 'CFP Franc', countries: 'French Polynesia, New Caledonia' },
  { code: 'IQD', name: 'Iraqi Dinar', countries: 'Iraq' },
  { code: 'IRR', name: 'Iranian Rial', countries: 'Iran' },
  { code: 'AFN', name: 'Afghan Afghani', countries: 'Afghanistan' },
  { code: 'LBP', name: 'Lebanese Pound', countries: 'Lebanon' },
  { code: 'SYP', name: 'Syrian Pound', countries: 'Syria' },
  { code: 'YER', name: 'Yemeni Rial', countries: 'Yemen' },
  { code: 'MNT', name: 'Mongolian Tugrik', countries: 'Mongolia' },
  { code: 'AMD', name: 'Armenian Dram', countries: 'Armenia' },
  { code: 'AZN', name: 'Azerbaijani Manat', countries: 'Azerbaijan' },
  { code: 'TJS', name: 'Tajikistani Somoni', countries: 'Tajikistan' },
  { code: 'TMT', name: 'Turkmenistani Manat', countries: 'Turkmenistan' },
  { code: 'KGS', name: 'Kyrgyzstani Som', countries: 'Kyrgyzstan' },
  { code: 'BND', name: 'Brunei Dollar', countries: 'Brunei' },
  { code: 'MOP', name: 'Macanese Pataca', countries: 'Macau' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', countries: 'Maldives' },
  { code: 'SCR', name: 'Seychellois Rupee', countries: 'Seychelles' },
  { code: 'GMD', name: 'Gambian Dalasi', countries: 'Gambia' },
  { code: 'SLL', name: 'Sierra Leonean Leone', countries: 'Sierra Leone' },
  { code: 'LRD', name: 'Liberian Dollar', countries: 'Liberia' },
  { code: 'GNF', name: 'Guinean Franc', countries: 'Guinea' },
  { code: 'MWK', name: 'Malawian Kwacha', countries: 'Malawi' },
  { code: 'SZL', name: 'Eswatini Lilangeni', countries: 'Eswatini, Swaziland' },
  { code: 'LSL', name: 'Lesotho Loti', countries: 'Lesotho' },
  { code: 'SDG', name: 'Sudanese Pound', countries: 'Sudan' },
  { code: 'SOS', name: 'Somali Shilling', countries: 'Somalia' },
  { code: 'DJF', name: 'Djiboutian Franc', countries: 'Djibouti' },
  { code: 'ERN', name: 'Eritrean Nakfa', countries: 'Eritrea' },
  { code: 'MDL', name: 'Moldovan Leu', countries: 'Moldova' },
  { code: 'ALL', name: 'Albanian Lek', countries: 'Albania' },
  { code: 'MKD', name: 'Macedonian Denar', countries: 'North Macedonia' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', countries: 'Bosnia and Herzegovina' },
  { code: 'BYN', name: 'Belarusian Ruble', countries: 'Belarus' },
  { code: 'CUP', name: 'Cuban Peso', countries: 'Cuba' },
  { code: 'HTG', name: 'Haitian Gourde', countries: 'Haiti' },
  { code: 'KPW', name: 'North Korean Won', countries: 'North Korea' },
];
