import type { TableColumnDef } from '../../hooks/usePersistedColumnVisibility';
import { TABLE_AUDIT_COLUMN_LABEL } from './columnLabels';

/** Extra optional columns (off by default) from drawer / list row data. */
const extra = (id: string, label: string): TableColumnDef => ({
  id,
  label,
  defaultVisible: false,
});

export const CANDIDATE_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'candidate', label: 'Candidate', locked: true },
  { id: 'roleCompany', label: 'Role / company' },
  { id: 'experience', label: 'Experience' },
  { id: 'location', label: 'Location' },
  { id: 'assignedJob', label: 'Assigned job' },
  { id: 'stage', label: 'Stage' },
  extra('email', 'Email'),
  extra('phone', 'Phone'),
  extra('source', 'Source'),
  extra('hotlist', 'Hotlist'),
  extra('rating', 'Rating'),
  extra('lastActivity', 'Last activity'),
  extra('skills', 'Skills'),
  extra('noticePeriod', 'Notice period'),
  extra('currentSalary', 'Current salary'),
  extra('expectedSalary', 'Expected salary'),
  extra('preferredLocation', 'Preferred location'),
  extra('education', 'Education'),
  extra('availability', 'Availability'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const JOB_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'title', label: 'Job title', locked: true },
  { id: 'client', label: 'Client' },
  { id: 'status', label: 'Status' },
  { id: 'pipeline', label: 'Pipeline' },
  { id: 'details', label: 'Details' },
  extra('location', 'Location'),
  extra('openings', 'Openings'),
  extra('owner', 'Recruiter'),
  extra('manager', 'Manager'),
  extra('createdDate', 'Created'),
  extra('priority', 'Priority'),
  extra('employmentType', 'Employment type'),
  extra('workMode', 'Work mode'),
  extra('jobLocationType', 'Location type'),
  extra('hot', 'Hot'),
  extra('aiMatch', 'AI match'),
  extra('experienceRequired', 'Experience required'),
  extra('industry', 'Category'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const LEAD_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'lead', label: 'Lead', locked: true },
  { id: 'source', label: 'Source' },
  { id: 'contact', label: 'Contact' },
  { id: 'status', label: 'Status' },
  { id: 'assignedTo', label: 'Assigned To' },
  { id: 'followUp', label: 'Last Follow-up' },
  extra('type', 'Lead type'),
  extra('priority', 'Priority'),
  extra('phone', 'Phone'),
  extra('industry', 'Industry'),
  extra('companySize', 'Company size'),
  extra('location', 'Location'),
  extra('website', 'Website'),
  extra('designation', 'Designation'),
  extra('needs', 'Services needed'),
  extra('expectedValue', 'Expected value'),
  extra('createdDate', 'Created'),
  extra('convertedClient', 'Converted client'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const CLIENT_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'client', label: 'Client Name', locked: true },
  { id: 'industry', label: 'Industry' },
  { id: 'location', label: 'Location' },
  { id: 'status', label: 'Status' },
  { id: 'owner', label: 'Team Member' },
  extra('openJobs', 'Open jobs'),
  extra('placements', 'Placements'),
  extra('lastActivity', 'Last activity'),
  extra('priority', 'Priority'),
  extra('companySize', 'Company size'),
  extra('revenue', 'Revenue'),
  extra('nextFollowUp', 'Next follow-up'),
  extra('clientSince', 'Client since'),
  extra('website', 'Website'),
  extra('timezone', 'Timezone'),
  extra('sla', 'SLA'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const CONTACT_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'contact', label: 'Contact Name', locked: true },
  { id: 'company', label: 'Company' },
  { id: 'designation', label: 'Designation' },
  { id: 'contactType', label: 'Contact Type' },
  { id: 'jobs', label: 'Jobs' },
  { id: 'owner', label: 'Owner' },
  { id: 'lastContact', label: 'Last Contact' },
  { id: 'status', label: 'Status' },
  extra('email', 'Email'),
  extra('phone', 'Phone'),
  extra('department', 'Department'),
  extra('location', 'Location'),
  extra('linkedin', 'LinkedIn'),
  extra('preferredChannel', 'Preferred channel'),
  extra('tags', 'Tags'),
  extra('isPrimary', 'Primary'),
  extra('createdAt', 'Created'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const INTERVIEW_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'candidate', label: 'Candidate', locked: true },
  { id: 'job', label: 'Job / client' },
  { id: 'round', label: 'Round' },
  { id: 'panel', label: 'Interviewers' },
  { id: 'status', label: 'Status' },
  extra('scheduled', 'Date / time'),
  extra('duration', 'Duration'),
  extra('type', 'Interview type'),
  extra('mode', 'Mode'),
  extra('platform', 'Meeting platform'),
  extra('location', 'Location'),
  extra('feedback', 'Feedback'),
  extra('createdBy', 'Created by'),
  extra('candidateStage', 'Candidate stage'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const PLACEMENT_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'candidate', label: 'Candidate', locked: true },
  { id: 'clientJob', label: 'Client / Job' },
  { id: 'recruiter', label: 'Team Member' },
  { id: 'offerDate', label: 'Offer Date' },
  { id: 'joiningDate', label: 'Joining Date' },
  { id: 'type', label: 'Type' },
  { id: 'status', label: 'Status' },
  extra('salary', 'Salary offered'),
  extra('fee', 'Placement fee'),
  extra('commission', 'Commission %'),
  extra('revenue', 'Revenue'),
  extra('paymentStatus', 'Payment'),
  extra('invoiceNumber', 'Invoice #'),
  extra('actualJoiningDate', 'Actual join'),
  extra('candidateEmail', 'Candidate email'),
  extra('reportingTo', 'Reporting to'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const MATCH_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'select', label: 'Select', locked: true },
  { id: 'candidate', label: 'Candidate', locked: true },
  { id: 'score', label: 'Match' },
  { id: 'roleCompany', label: 'Role / company' },
  { id: 'experience', label: 'Experience' },
  { id: 'location', label: 'Location' },
  { id: 'status', label: 'Status' },
  extra('noticePeriod', 'Notice period'),
  extra('salary', 'Expected salary'),
  extra('email', 'Email'),
  extra('phone', 'Phone'),
  extra('matchSource', 'Match source'),
  extra('matchRating', 'Rating'),
  extra('savedAt', 'Saved'),
  { id: 'actions', label: 'Actions', locked: true },
];

export const TASK_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'task', label: 'Task Title', locked: true },
  { id: 'type', label: 'Type' },
  { id: 'related', label: 'Related To' },
  { id: 'due', label: 'Due Date' },
  { id: 'priority', label: 'Priority' },
  { id: 'status', label: 'Status' },
  { id: 'createdBy', label: 'Created by' },
  { id: 'assignee', label: 'Assigned to' },
  { id: 'delegated', label: 'Delegated to' },
  extra('time', 'Due time'),
  extra('relatedType', 'Related type'),
  { id: 'audit', label: TABLE_AUDIT_COLUMN_LABEL },
  { id: 'actions', label: 'Actions', locked: true },
];

export const PIPELINE_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'candidate', label: 'Candidate', locked: true },
  { id: 'stage', label: 'Stage' },
  { id: 'clientJob', label: 'Client & Job' },
  { id: 'status', label: 'Status' },
  { id: 'lastActivity', label: 'Last Activity' },
  extra('owner', 'Team member'),
  extra('experience', 'Experience'),
  extra('location', 'Location'),
  extra('followUp', 'Follow-up'),
  extra('job', 'Job'),
  extra('client', 'Client'),
];

export const TEAM_TABLE_COLUMNS: TableColumnDef[] = [
  { id: 'member', label: 'Member', locked: true },
  { id: 'role', label: 'Role' },
  { id: 'department', label: 'Department' },
  { id: 'rank', label: 'Rank' },
  { id: 'email', label: 'Email' },
  { id: 'assignedLeads', label: 'Assigned leads' },
  { id: 'credential', label: 'Credential' },
  { id: 'status', label: 'Status' },
  extra('phone', 'Phone'),
  extra('location', 'Location'),
  extra('designation', 'Designation'),
  extra('manager', 'Manager'),
  extra('tasks', 'Tasks'),
  extra('lastLogin', 'Last login'),
  extra('createdAt', 'Created'),
  { id: 'actions', label: 'Actions', locked: true },
];
